# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version for the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Specify the path to your Sphinx configuration file
sphinx:
  configuration: docs/source/conf.py

# Instruct Read the Docs to install your project and its doc dependencies
# from the generated requirements.txt file.
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
