"""
Observation operators for Tide Gauge networks.

These operators map the composite physical response fields generated by the
SeaLevelEquation into discrete Relative Sea Level Change observations at
specific geographic coordinates.
"""

from __future__ import annotations
import csv
from typing import Callable, List, Optional, Tuple

from pyslfp.data.downloader import ensure_data
from pygeoinf import LinearOperator, HilbertSpaceDirectSum, RowLinearOperator

from .utils import check_response_space


def read_gloss_tide_gauge_data(
    filter_func: Optional[Callable[[str, float, float], bool]] = None,
) -> Tuple[List[str], List[Tuple[float, float]]]:
    """
    Reads and parses the GLOSS tide gauge network coordinates and names.

    Automatically fetches the GLOSS dataset from Zenodo if not present locally.

    Args:
        filter_func: An optional callable that takes (name, lat, lon) and
            returns True if the station should be included, False otherwise.

    Returns:
        Tuple[List[str], List[Tuple[float, float]]]: Two lists containing the
            station names and their corresponding (latitude, longitude) tuples.
    """
    data_dir = ensure_data("TIDE_GAUGE")
    file_path = data_dir / "gloss_full.txt"

    names: List[str] = []
    points: List[Tuple[float, float]] = []

    # Using encoding="utf-8" to handle special characters in international names.
    with open(file_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)

        # Skip the header row
        next(reader, None)

        for row in reader:
            if len(row) >= 5:
                name = row[0].strip()
                lat = float(row[3])
                lon = float(row[4])

                # Apply the filter if one was provided
                if filter_func is None or filter_func(name, lat, lon):
                    names.append(name)
                    points.append((lat, lon))

    return names, points


def tide_gauge_operator(
    response_space: HilbertSpaceDirectSum, points: List[Tuple[float, float]], /
) -> LinearOperator:
    """
    Maps the response fields to a vector of sea level change values at discrete locations.

    Tide gauges measure relative sea level change, which corresponds to the
    first component (subspace 0) of the response space.

    Args:
        response_space (HilbertSpaceDirectSum): The 4-component response space
            [SLC, Disp, GPC, AVC].
        points (List[Tuple[float, float]]): A list of (latitude, longitude)
            observation coordinates in degrees.

    Returns:
        LinearOperator: A mapping from the response space to an N-dimensional
            Euclidean observation space.

    Raises:
        ValueError: If the response space is malformed or lacks sufficient
            regularity for point evaluation.
    """
    # Use the shared utility to validate the response space structure
    # and ensure it supports point evaluation.
    check_response_space(response_space, point_values=True)

    # Extract the necessary subspaces
    field_space = response_space.subspace(0)
    euclidean_space = response_space.subspace(3)

    # Construct the point evaluation mapping for the SLC component
    point_evaluation_operator = field_space.point_evaluation_operator(points)
    codomain = point_evaluation_operator.codomain

    # Assemble the full block row operator.
    # Only the SLC component (index 0) contributes to the observation.
    return RowLinearOperator(
        [
            point_evaluation_operator,
            field_space.zero_operator(codomain=codomain),
            field_space.zero_operator(codomain=codomain),
            euclidean_space.zero_operator(codomain=codomain),
        ]
    )
