"""
Observation operators for Tide Gauge networks.

These operators map the composite physical response fields generated by the
SeaLevelEquation into discrete Relative Sea Level Change observations at
specific geographic coordinates.
"""

from __future__ import annotations
from typing import List, Tuple

from pygeoinf import LinearOperator, HilbertSpaceDirectSum, RowLinearOperator
from .utils import check_response_space


def tide_gauge_operator(
    response_space: HilbertSpaceDirectSum, points: List[Tuple[float, float]], /
) -> LinearOperator:
    """
    Maps the response fields to a vector of sea level change values at discrete locations.

    Tide gauges measure relative sea level change, which corresponds to the
    first component (subspace 0) of the response space.

    Args:
        response_space (HilbertSpaceDirectSum): The 4-component response space
            [SLC, Disp, GPC, AVC].
        points (List[Tuple[float, float]]): A list of (latitude, longitude)
            observation coordinates in degrees.

    Returns:
        LinearOperator: A mapping from the response space to an N-dimensional
            Euclidean observation space.

    Raises:
        ValueError: If the response space is malformed or lacks sufficient
            regularity for point evaluation.
    """
    # Use the shared utility to validate the response space structure
    # and ensure it supports point evaluation.
    check_response_space(response_space, point_values=True)

    # Extract the necessary subspaces
    field_space = response_space.subspace(0)
    euclidean_space = response_space.subspace(3)

    # Construct the point evaluation mapping for the SLC component
    point_evaluation_operator = field_space.point_evaluation_operator(points)
    codomain = point_evaluation_operator.codomain

    # Assemble the full block row operator.
    # Only the SLC component (index 0) contributes to the observation.
    return RowLinearOperator(
        [
            point_evaluation_operator,
            field_space.zero_operator(codomain=codomain),
            field_space.zero_operator(codomain=codomain),
            euclidean_space.zero_operator(codomain=codomain),
        ]
    )
