"""
Observation models and operators for Tide Gauge networks.

These operators map the composite physical response fields generated by the
SeaLevelEquation into discrete Relative Sea Level Change observations at
specific geographic coordinates.
"""

from __future__ import annotations
import csv
from typing import Callable, List, Optional, Tuple


from pygeoinf import (
    LinearOperator,
    HilbertSpaceDirectSum,
)

from pyslfp.data.downloader import ensure_data
from pyslfp.linear_operators.utils import check_response_space
from pyslfp.linear_operators.physics import FingerPrintOperator


# ================================================================ #
#                       Data Loaders                               #
# ================================================================ #


def read_gloss_tide_gauge_data(
    *,
    filter_func: Optional[Callable[[str, float, float], bool]] = None,
) -> Tuple[List[str], List[Tuple[float, float]]]:
    """
    Reads and parses the GLOSS tide gauge network coordinates and names.

    Automatically fetches the GLOSS dataset from Zenodo if not present locally.

    Args:
        filter_func: An optional callable that takes (name, lat, lon) and
            returns True if the station should be included, False otherwise.

    Returns:
        Two lists containing the station names and their corresponding
        (latitude, longitude) tuples.
    """
    data_dir = ensure_data("TIDE_GAUGE")
    file_path = data_dir / "gloss_full.txt"

    names: List[str] = []
    points: List[Tuple[float, float]] = []

    # Using encoding="utf-8" to handle special characters in international names.
    with open(file_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader, None)  # Skip the header row

        for row in reader:
            if len(row) >= 5:
                name = row[0].strip()
                lat = float(row[3])
                lon = float(row[4])

                if filter_func is None or filter_func(name, lat, lon):
                    names.append(name)
                    points.append((lat, lon))

    return names, points


# ================================================================ #
#                       Raw Math Operators                         #
# ================================================================ #


def tide_gauge_operator(
    response_space: HilbertSpaceDirectSum, points: List[Tuple[float, float]], /
) -> LinearOperator:
    """
    Maps the response fields to a vector of sea level change values at discrete locations.

    Tide gauges measure relative sea level change, which corresponds to the
    first component (subspace 0) of the response space.

    Args:
        response_space: The 4-component response space [SLC, Disp, GPC, AVC].
        points: A list of (latitude, longitude) observation coordinates in degrees.

    Returns:
        A mapping from the response space to an N-dimensional Euclidean observation space.
    """
    check_response_space(response_space, point_values=True)

    point_evaluation_operator = response_space.subspace(0).point_evaluation_operator(
        points
    )

    return point_evaluation_operator @ response_space.subspace_projection(0)


# ================================================================ #
#                     Observation Models                           #
# ================================================================ #


class TideGaugeObservationModel:
    """
    An observation model that links surface mass loads directly to relative
    sea level change measured at discrete tide gauge locations.
    """

    def __init__(
        self,
        fingerprint_operator: FingerPrintOperator,
        points: List[Tuple[float, float]],
        /,
        *,
        names: Optional[List[str]] = None,
    ):
        """
        Args:
            fingerprint_operator: The physics operator that maps loads to Earth responses.
            points: A list of (latitude, longitude) observation coordinates in degrees.
            names: An optional list of station names corresponding to the points.
        """
        self._fingerprint_operator = fingerprint_operator
        self._points = points
        self._names = (
            names if names is not None else [f"Station_{i}" for i in range(len(points))]
        )

        # 1. The spatial extraction operator (Response Space -> Euclidean Space)
        self._response_to_data_operator = tide_gauge_operator(
            self.fingerprint_operator.codomain, self.points
        )

        # 2. The full composite forward operator (Load Space -> Euclidean Space)
        self._forward_operator = (
            self._response_to_data_operator @ self.fingerprint_operator
        )

    @classmethod
    def from_gloss_network(
        cls,
        fingerprint_operator: FingerPrintOperator,
        /,
        *,
        filter_func: Optional[Callable[[str, float, float], bool]] = None,
    ) -> TideGaugeObservationModel:
        """
        Instantiates the observation model using the global GLOSS tide gauge network.

        Args:
            fingerprint_operator: The physics operator mapping loads to Earth responses.
            filter_func: An optional callable to filter stations by (name, lat, lon).
        """
        names, points = read_gloss_tide_gauge_data(filter_func=filter_func)
        return cls(fingerprint_operator, points, names=names)

    @property
    def fingerprint_operator(self) -> FingerPrintOperator:
        """
        Returns the associated FingerPrintOperator instance.
        """
        return self._fingerprint_operator

    @property
    def points(self) -> List[Tuple[float, float]]:
        """
        Returns a list of the observation points
        """
        return self._points

    @property
    def names(self) -> List[str]:
        """
        Returns a list of the names for the observation points.
        """
        return self._names

    @property
    def forward_operator(self) -> LinearOperator:
        """
        Returns the forward operator mapping direct loads to tide gauge observations.
        """
        return self._forward_operator
