"""
Test suite for the AnalyticalIceModel.
"""

import numpy as np
from pyshtools import SHGrid
from pyslfp.ice.analytical_ice import AnalyticalIceModel


def test_analytical_grid_shapes_and_wrappers():
    """
    Tests that the analytical model returns valid SHGrid objects of the correct
    shape, and that the convenience wrappers (get_ice_thickness, get_sea_level) work.
    """
    lmax = 32
    model = AnalyticalIceModel()

    # Test joint return
    ice, sl = model.get_ice_thickness_and_sea_level(0.0, lmax)
    assert isinstance(ice, SHGrid)
    assert isinstance(sl, SHGrid)
    assert ice.lmax == lmax
    assert sl.lmax == lmax

    # Test wrappers
    ice_only = model.get_ice_thickness(0.0, lmax)
    sl_only = model.get_sea_level(0.0, lmax)

    assert np.allclose(ice.data, ice_only.data)
    assert np.allclose(sl.data, sl_only.data)


def test_analytical_ice_geography():
    """
    Sanity check to ensure the analytical geography generated by the
    Super-Gaussians puts ice and land roughly where expected.
    """
    lmax = 64
    model = AnalyticalIceModel()
    ice, sl = model.get_ice_thickness_and_sea_level(0.0, lmax)

    lats = ice.lats()
    lons = ice.lons()

    # North Pole (lat=90) should have thick ice
    np_lat_idx = np.argmax(lats)
    assert np.all(ice.data[np_lat_idx, :] > 1000.0)

    # Equator at lon=0 should be ocean (sea level > 0, ice = 0)
    eq_lat_idx = np.argmin(np.abs(lats - 0.0))
    eq_lon_idx = np.argmin(np.abs(lons - 0.0))
    assert np.isclose(ice.data[eq_lat_idx, eq_lon_idx], 0.0)
    assert sl.data[eq_lat_idx, eq_lon_idx] > 1000.0


def test_analytical_ice_evolution():
    """Tests that the LGM (date=21.0) has strictly more ice than present day (date=0.0)."""
    lmax = 16
    model = AnalyticalIceModel()

    ice_present = model.get_ice_thickness(0.0, lmax)
    ice_lgm = model.get_ice_thickness(21.0, lmax)

    assert np.sum(ice_lgm.data) > np.sum(ice_present.data)
